### ISSUE TITLE
Showing line numbers on your example

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.TinyMCE#1]
I just tried your example [here](https://tinymce.enlighterjs.org) but even though line numbers is ticked, I see no line numbers:

![EnlighterJS-TinyMCE](https://user-images.githubusercontent.com/7985331/74719521-1904b900-522c-11ea-96d3-1d4c4af039aa.png)

Can you please clarify? Thanks.

**Comment by AndiDittrich** [comment]
linenumbers are a feature of the **syntax highlighter** and not of the editing plugins - this is just plain text

**Comment by ajtruckle** [comment]
Understood.
