### ISSUE TITLE
TinyMCE plugin feedback

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.TinyMCE#10]
Please see:

![Window](https://user-images.githubusercontent.com/7985331/79553640-afbaee00-8094-11ea-8ddd-52ab579b2f2d.png)

1. **Theme**.
Is it possible for me to omit the Theme option from the window? Not all themes are displaying good in my support forum and if possible I would like to lock down the theme that anyone uses to Atomic.

2. **Linennumber offset**
There are two issues here:
- It has a typo  error because it should be **Line number offset** or maybe **Start with line number**.
- It makes sense that this control comes **before** the **Point out Lines** control.

3. **Show Linennumbers**
This has a typo. It should really be **Show Line numbers**.

4. **Point out Lines**
I wonder if it is better to phrase this option as "Lines to highlight".

To me, I reckon:

- Display line numbers
- Begin with line number
- Lines to highlight

It is obviously entirely your decision but there are two typos and it makes sense to swap the two controls around I think.

**Comment by ajtruckle** [comment]
Thanks. Looking at the documentation then I would use something like this to remove all unwanted themes:

```
// add a custom filter to modify the theme list
add_filter('enlighter_themes', function($themes){
    // DEBUG: just display the dataset - uncomment the following line to debug issues
    // echo '<pre>', print_r($themes, true), '</pre>';

    // unset the theme
    unset($themes['godzilla']);

    return $themes;
});
```
I assume that **Standard (Atomic)** will automatically show.

**Comment by AndiDittrich** [comment]
just return an array with 1 entry..thats more solid/future proof

**Comment by ajtruckle** [comment]
Ah, like:

```
// add a custom filter to modify the theme list
add_filter('enlighter_themes', function ($themes){
    // DEBUG: just display the dataset - uncomment the following line to debug issues
    // echo '<pre>', print_r($themes, true), '</pre>';

    // just show the Classic + Enlighter Theme 
    // Add a new custom theme named my_c_theme - shown as 'MyCustom Lalala Themes' in select boxes
    // Note: Custom themes CSS has to be loaded separately
    return array(
        'atomic' => 'Atomic',
     );
});
```

**Comment by AndiDittrich** [comment]
an empty array should also work in TinyMCE => theme not set => defaults are used

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/79556667-ae43f280-80a1-11ea-9928-f0583a1ff017.png)

**Comment by ajtruckle** [comment]
Looks good!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
> an empty array should also work in TinyMCE => theme not set => defaults are used

That works great!
