### ISSUE TITLE
The height of the code view

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.TinyMCE#11]
Hi!

Please see this page:

https://www.publictalksoftware.co.uk/videos/using-custom-dates-on-s-140-schedule/

At the moment I have a hyperlink to a external code file. If I convert this into a EnlighterJS code block it becomes a big view. Is it possible for just this code snippet to display it with vertical scroll bar so that it is not so large?

**Comment by AndiDittrich** [comment]
Hi,

you want to change the TinyMCE "Enlighter" block size ?

**Comment by ajtruckle** [comment]
Yes, that is what I meant! You said it much simpler. But just on that page if possible.

**Comment by AndiDittrich** [comment]
on a particular page...that's going to be difficult...

the "block" in TinyMCE is just the `<pre>` tag which is used by EnlighterJS. you can add custom editor styles to TinyMCE and use the `max-height` as well as `overflow: scroll` css attribute.

limiting these settings to a page can be done via the page-id/post-id or the path

**Comment by ajtruckle** [comment]
Ok, I may have a look. Thanks for the explanation.
