### ISSUE TITLE
Feature Request: Highlight lines when creating the code snippet

### ISSUE THREAD

**Issue by gcraig14** [EnlighterJS/Plugin.TinyMCE#3]
Currently we can highlight specific lines in Enlighter, but only as an edit after creation. Ideally we can highlight the desired lines as part of the creation dialog.
Need an ability to highlight the desired lines as part of the creation dialog.

**Comment by ajtruckle** [comment]
> it's a bit difficult because it will mess up the code insert dialog - the design goal was to avoid this

This was what I was thinking. Isn’t a hardship to click another button rather than bloat your code.
