### ISSUE TITLE
Feature Request: Easier way to remove a EnlighterJS "block" from TinyMCE

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.TinyMCE#4]
At the moment, if I decide that I want to remove an inserted EnlighterJS block of code I have to select all the code and the header banner etc. to delete it. This is not a hardship of course!

But could it be possible that when you click the "Edit Code" button that it offer to "Remove Block"?

I have no idea what is involved.

**Comment by ajtruckle** [comment]
> that should be technically possible. but it's maybe more effective to add an additional button next to the codeblock-edit buttons which appear on mouseover

Whatever is most practical for you to implement.

**Comment by AndiDittrich** [comment]
![tinymce_delete_coeblock](https://user-images.githubusercontent.com/1474107/74831940-8856d780-5316-11ea-822e-2e78cc3386cf.gif)

**Comment by ajtruckle** [comment]
This is really great! Nice and simple. I like it. Will this be in the existing WordPress Plugin as an update or only in the v4 beta?

**Comment by AndiDittrich** [comment]
v4 only
