### ISSUE TITLE
Typo - Line number offset

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.TinyMCE#5]
Have a look here:

![linenumber-offset](https://user-images.githubusercontent.com/7985331/74820236-964a2f80-52f9-11ea-8221-38dd54f774cd.png)

**Linennumber** needs to be **Linenumber**. Technically speaking, in English it should really be **Line number**.

**Comment by AndiDittrich** [comment]
(i'm not a native speaker) is `Line number` or `Line numbering` the correct phrasing ?

**Comment by ajtruckle** [comment]
> (i'm not a native speaker) is `Line number` or `Line numbering` the correct phrasing ?

I suppose some of this is down to personal taste. You have several choices IMHO.

**Show Linenumbers**

- Show Line Numbers
- Include Line Numbers
- Display Line Numbers

**Linenumber offset (e.g. 5)**

- Line Number offset (e.g. 5)
- First Line Number (e.g. 5)
- Start line numbering from (e.g. 5)

Either way, in answer to your question I think **Line number/s** is fine. There is grammatically only one instance where you would use **numbering**.
