### ISSUE TITLE
Feature request - Hide the Theme label and drop-down list

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.TinyMCE#6]
Please look:

![enlighterjs-theme](https://user-images.githubusercontent.com/7985331/74820440-e9bc7d80-52f9-11ea-8740-85180bc1bd3f.png)

I don't want any users selecting a different **theme** that the default. they won't know what the themes are anyway, and some of them don't render well due to issues with my WordPress theme. Also, I would like consistency across the site so that if I change my mind in what theme I use it will be applied everywhere.

So that this setting be visually removed?

**Comment by AndiDittrich** [comment]
you can rebuild the plugin and remove the specific line - there is no user controllable feature projected.
as a workaround, you can alter the themelist and just set 1 theme to be active

**Comment by ajtruckle** [comment]
> you can rebuild the plugin and remove the specific line

The above sounds complicated for me and then I foresee a maintenance issue with new upgrades to your plugin.



> as a workaround, you can alter the themelist and just set 1 theme to be active

This idea does sound viable to me. Now I got to find in your documents how to do it.

**Comment by ajtruckle** [comment]
I found the sample code:

```
function mm_ejs_themes($themes){
    // just show the Classic + Enlighter Theme 
    // Add a new custom theme named my_c_theme - shown as 'MyCustom Lalala Themes' in select boxes
    // Note: Custom themes CSS has to be loaded separately
    return array(
         'Classic' => 'classic',
         'Enlighter' => 'enlighter'
         'MyCustom Lalala Themes' => 'my_c_theme'
     );
}

// add a custom filter to modify the theme list
add_filter('enlighter_themes', 'mm_ejs_themes');
```
At the moment I am using `WPCustom` so is the id `wpcustom`?

**Comment by AndiDittrich** [comment]
use `print_r` to view the content of the `$theme` array

**Comment by ajtruckle** [comment]
Confirmed:

```
Array
(
    [WPCustom] =&gt; wpcustom
    [Enlighter] =&gt; enlighter
    [Godzilla] =&gt; godzilla
    [Beyond] =&gt; beyond
    [Classic] =&gt; classic
    [MooTwo] =&gt; mootwo
    [Eclipse] =&gt; eclipse
    [Droide] =&gt; droide
    [Minimal] =&gt; minimal
    [Atomic] =&gt; atomic
    [Rowhammer] =&gt; rowhammer
    [Git] =&gt; git
    [Mocha] =&gt; mocha
    [MooTools] =&gt; mootools
    [Panic] =&gt; panic
    [Tutti] =&gt; tutti
    [Twilight] =&gt; twilight
)

```

**Comment by ajtruckle** [comment]
Although it is still a moot point because even if you use the sample and include one or two themes it will still be preceded by "Default (Global settings)" so this option (for both theme and programming language) are outside of this array list.

**Comment by AndiDittrich** [comment]
the "default" language setting has been removed in v4 - therefore it doesn't matter anymore

**Comment by ajtruckle** [comment]
Understood. I look forward to test driving v4 for you when it is operation and stable with bbPress 2.6.x.

**Comment by AndiDittrich** [comment]
did you tried it after applying the changes to your site ? it should work..

**Comment by ajtruckle** [comment]
> did you tried it after applying the changes to your site ? it should work..

What changes? If you recall, you got me to switch on the "bbPress" option in the backend but nothing was working for me. Or has something since changed?

**Comment by AndiDittrich** [comment]
no but the v3 plugin didn't work on your site too because of the weak css rules. if your happy with v3 leave it as is for now

**Comment by ajtruckle** [comment]
> no but the v3 plugin didn't work on your site too because of the weak css rules. if your happy with v3 leave it as is for now

I am happy with the one I have for now. The only reason I would like to upgrade is before of the fact that the popup toolbar does not display when you hover the mouse over the code and the current line of code does not highlight. Whilst this is not a big issue it does mean that I have to remember to attach the code as a raw attachment for now in the forum topic.

**Comment by AndiDittrich** [comment]
i can't follow you - mouseover on the current line is fully supported in EnlighterJS v2 and implemented by all official themes - see https://enlighterjs.org/Theme.Droide.html

**Comment by ajtruckle** [comment]
But as you already told me, bbPress conflicts with it and classes need disabling for it to function.  And you told me v4 does not have the conflict issue. Thus, I stated this is the reason why I would like v4 beta because of avoiding this conflict issue. Remember now?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AndiDittrich** [comment]
i know but you can still override the bbPress styles or fix them. it's not an issue with the plugin itself...

**Comment by ajtruckle** [comment]
I don’t know what affect overriding those styles will have. I do t want to fight the system.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
