### ISSUE TITLE
Feedback — bbPress replies and styling

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.TinyMCE#8]
This is just feedback for you. Today I was trying to use the TinyMCE approach to insert some XSL script into a reply to a topic. It did not like it. In the edit I had to set it as text editor mode and use a `[xml]` shortcode. It worked fine:

![enlighter-styling](https://user-images.githubusercontent.com/7985331/75152727-a00cd200-5701-11ea-8a4b-01e37aba6aa1.png)

I am only providing this as feedback and not worried about it too much. Do you have a ETA for testing your next V4 BETA?

**Comment by AndiDittrich** [comment]
whats not working and what did you expect ?

you can download the current development version anytime from GitHub - the changes related to EnlighterJS not published until v3.2 has been finished

**Comment by ajtruckle** [comment]
> whats not working and what did you expect ?

Do you remember when I was getting rendering problems of the sample code and the line numbers were just showing as bullets. It was like that. And when I went to edit the reply (in Visual mode) it was not decoding the post correctly and leaving some of the sample code as normal text. But let us not worry.

As I mentioned, by using the shortcode route it was robust. If I get the issue with the eventual V4BETA then I will raise it at that time.

> you can download the current development version anytime from GitHub - the changes related to EnlighterJS not published until v3.2 has been finished

Yes, but I need to wait don't I, as I need the v3.2 changes (as you mentioned in other associated issue I raised).

**Comment by AndiDittrich** [comment]
never switch between visual editor and text mode - never use shortcodes in visual mode.....otherwise it can cause an unpredictable behaviour! this is not related to Enlighter.TinyMCE...it is a general issue in WordPress/bbPress.

my recommendation is still to modify the bbPress styles to avoid any of the styling issues in the future

**Comment by ajtruckle** [comment]
In this case i did not switch between editor modes. I had inserted it as visual and was edited as visual. That was when it did not display right and did not subsequently edit right. This was why I had no choice but to go to text mode and delete the pre block etc and do it as a shortcode which was fine. I do remember your rule of not switching editors. I just didn't expect an issue because all samples so far have always worked fine in the TinyMCE mode.

> my recommendation is still to modify the bbPress styles to avoid any of the styling issues in the future

And I think this is a good recommendation. I think though that these issues relate to the bbPress "style pack" I am using. Because clearly you beta tested bbPress when you released it and it was fine. So it is having this added layer of bbp style pack inbetween bbPress and enlighter causing some of the agro.

But on the whole, despite the glitches, I am very happy. If I have to deal with style issues with V4BETA then I will raise the issue with bbp style pack for help. But not until then.

**Comment by AndiDittrich** [comment]
could you please provide a minimal step-by-step example (including the code) howto reproduce this behaviour in visual editor mode ?

**Comment by ajtruckle** [comment]
Just tried and I can't Even in TinyMCE mode is OK. How strange.  Close this.
